name: Deploy Static Site

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Verify Deployment Directory
    # Optional: Ensure your files are in the correct location (root folder)
    - name: Ensure Static Files Exist
      run: |
        ls -la # List files for debugging

    # Step 3: Skip gh-pages Step
    # Since you are deploying directly from `main`, you do not need to push files to a different branch.
