name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

permissions:
  contents: write  # Ensure GitHub Actions can write to the branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Optional: Build the project (skip if not needed)
      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm install
            npm run build
          fi

      # Step 3: Deploy to the main branch
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update site on push to main branch" || echo "No changes to commit"
          git push origin main
